
server:
  port: 2520 # 网关端口
spring:
  application:
    name: shenshanshi-gateway # 服务名称
  cloud:
    nacos:
      server-addr: niconiconi:8848 # nacos地址
      discovery:
        username: nacos
        password: 770520
        namespace: public



    gateway:
      routes: # 网关路由配置
        - id: shenshanshi-account  #账户服务
          uri: lb://shenshanshi-account
          predicates:
            - Path=/account/**

        - id: shenshanshi-oauth  #认证服务
          uri: lb://shenshanshi-oauth
          predicates:
            - Path=/login,/logout,/register

        - id: shenshanshi-forum  #论坛服务
          uri: lb://shenshanshi-forum
          predicates:
            - Path=/forum/**