server:
  port: 2521

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: shenshanshi-account
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://niconiconi:3306/shenshanshi?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 770520
  redis:
    host: niconiconi
    port: 6379
  cloud:
    nacos:
      server-addr: niconiconi:8848
      discovery:
        username: nacos
        password: 770520
        namespace: public

